# This file enables core functionality

esp8266:
  board: $board

esphome:
  name: $node_name
  project:
    name: "dentra.ewh"
    version: $ewh_version

logger:
  # Disable debug loggin of standard components
  logs:
    api: INFO
    button: INFO
    switch: INFO
    sensor: INFO
    select: INFO
    number: INFO
    climate: INFO
    text_sensor: INFO
    binary_sensor: INFO

wifi:
  ssid: $wifi_ssid
  password: $wifi_password
  ap:
    ssid: "$name Fallback Hotspot"
    password: $wifi_ap_password

captive_portal:
ota:
api:

time:
  platform: $time_platform

sensor:
  - platform: wifi_signal
    name: "$name WiFi Signal"

button:
  - platform: restart
    name: "$name Restart"
